name: ci-cd

on:
  push:
    branches:
      - main
    tags:
      - *
  pull_requests:
    banches:
      - main


jobs:

  tox-job:
    name: Run "tox -e ${{ matrix.tox-env }}" for python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
        tox-env: ['lint', 'typecheck', 'func']
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox=4.31.0
    - name: Run env
      run: tox -e ${{ matrix.tox-env }}

  # https://github.com/marketplace/actions/alls-green
  check:  # This job does nothing and is only used for the branch protection
    if: always()
    outputs:
      result: ${{ steps.all-green.outputs.result }}
    needs:
      - tox-job
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs) }}


  pypi-publish:
    name: upload release to PyPI
    needs: [check]
    if: needs.check.outputs.result == 'success' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      - name: Install build
        run: pip install -U build
      - name: Build wheel
        run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
